language: python
python:
  - "3.6"

# command to install dependencies
install:
 - pip install -r requirements-dev.txt
 - pip install -e .
 - pip install codecov

# command to run tests
script:
 - python -m pytest --cov=redditdownload --cov-config=.coveragerc -m "not no_travis"
after_success:
 - codecov
